name: build

on:
  push:
  pull_request:
    branches: [main]
    paths:
      - "**.fs"
      - "**.fsproj"

env:
  DOTNET_VERSION: "7.0.400" # The .NET SDK version to use

jobs:
  build:
    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: paket-cache
          key: ${{ runner.os }}-paket-${{ hashFiles('paket.lock') }}
          restore-keys: |
            ${{ runner.os }}-paket-

      - name: Install buildtools
        run: dotnet tool restore

      - name: Install dependencies
        run: dotnet paket restore && dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore
