name: Publish MyGet Packages

on:
  push:
    tags:
      - 'myget-v*'

env:
  DOTNET_VERSION: ${{ vars.DOTNET_VERSION }}

jobs:
  publish_upload:
    name: Publish MyGet Packages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install buildtools
        run: dotnet tool restore

      - name: Install dependencies
        run: dotnet paket restore

      - name: Pack and upload NuGet package
        run: |
          dotnet pack -c Release
          dotnet nuget push Aurum/bin/Release/*.nupkg --skip-duplicate --no-symbols -s https://www.myget.org/F/aurum/api/v3/index.json -k ${{ secrets.MYGET_API_KEY }}
          dotnet nuget push Aurum.*/bin/Release/*.nupkg --skip-duplicate --no-symbols -s https://www.myget.org/F/aurum/api/v3/index.json -k ${{ secrets.MYGET_API_KEY }}
